import { env } from '../env.mjs';

export const siteConfig = {
  title: 'Julia A • Developer Portfolio',
  name: 'Julia A',
  description: 'The personal portfolio of Julia A',
  keywords: [
    // ──────────────── 🧑‍💻 Portfolio & Personal Brand ────────────────
    'Julia A',
    'Julia A Portfolio',
    'Julia Portfolio',
    'Portfolio Website',
    'Personal Portfolio',
    'Developer Portfolio',
    'Frontend Portfolio',
    'Creative Developer Portfolio',
    'Modern Portfolio Design',
    'Next.js Portfolio',
    'React Portfolio',
    'Professional Portfolio',
    'Software Engineer Portfolio',

    // ──────────────── 🌐 Web Development & Frontend ────────────────
    'Front-end Developer',
    'React Developer',
    'Next.js Developer',
    'JavaScript Developer',
    'TypeScript Developer',
    'Web Developer',
    'Frontend Engineer',
    'UI Developer',
    'Web Development',
    'Frontend Development',
    'Responsive Web Design',
    'Website Development',
    'Web Applications',
    'Modern Web Apps',
    'Progressive Web Apps',
    'Web Performance Optimization',
    'Accessibility in Web Design',
    'Semantic HTML',
    'CSS Expert',

    // ──────────────── 🎨 UI / UX & Design ────────────────
    'UI/UX Design',
    'User Interface Engineer',
    'User Experience Designer',
    'Tailwind CSS',
    'Framer Motion',
    'Shadcn UI',
    'Responsive UI',
    'Design Systems',
    'Component Design',
    'Interactive UI',
    'Visual Design',
    'Aesthetic Web Design',
    'Creative UI Developer',

    // ──────────────── ⚙️ Tools, Frameworks & Tech Stack ────────────────
    'React',
    'Next.js',
    'TypeScript',
    'JavaScript',
    'Node.js',
    'Tailwind CSS',
    'Framer Motion',
    'Lucide Icons',
    'Vercel',
    'GitHub Actions',
    'Husky',
    'Prettier',
    'ESLint',
    'Mongoose',
    'Zod',
    'Env Validation',
    'Server Components',
    'Next.js App Router',
    'SEO Optimization',

    // ──────────────── 🚀 Career & Industry ────────────────
    'Front-end Engineer India',
    'Software Developer India',
    'Web Developer Delhi',
    'Tech Enthusiast',
    'Freelance Developer',
    'Freelance Frontend Developer',
    'Open Source Developer',
    'Next.js Freelancer',
    'React Freelancer',
    'Frontend Specialist',
    'Performance-Oriented Developer',
    'Full Stack Enthusiast',
    'UI Developer Delhi',

    // ──────────────── 💡 Soft Skills & Personal Traits ────────────────
    'Creative Problem Solver',
    'Clean Code Advocate',
    'Modern Design Thinker',
    'Tech Enthusiast',
    'Continuous Learner',
    'Innovative Developer',
    'Collaborative Engineer',
    'Design-minded Developer',

    // ──────────────── 🔍 SEO & Meta Context ────────────────
    'Portfolio Website SEO',
    'Personal Branding Developer',
    'Next.js SEO',
    'Open Graph Optimization',
    'Meta Tags Optimization',
    'Structured Data',
    'Schema.org Portfolio',
    'Google Search Optimization',
  ],

  url: env.SITE_URL || 'https://dark-portfolio-site.vercel.app/',
  ogImage: `${env.SITE_URL || 'https://dark-portfolio-site.vercel.app/'}/og-image.png`,
  twitterHandle: '@psparwez',
  locale: 'en_IN',
  author: {
    name: 'Julia A',
    url: 'https://dark-portfolio-site.vercel.app/',
    email: process.env.CONTACT_EMAIL,
  },
  themeColor: '#0f172a',
  googleSiteVerificationId: '', // TODO

  //  <Metadata>
  metadata: {
    title: 'Julia A • Developer Portfolio',
    description: 'Explore the work, projects, and achievements of Julia A',
    openGraph: {
      type: 'website',
      url: env.SITE_URL,
      title: 'Julia A • Developer Portfolio',
      description: 'Explore the work, projects, and achievements of Julia A ',
      siteName: 'Julia A',

      images: [
        {
          url: `${env.SITE_URL}/og-image.png`,
          width: 1200,
          height: 630,
          alt: 'Julia A Portfolio Preview',
        },
      ],
      locale: 'en_IN',
    },
    twitter: {
      card: 'summary_large_image',
      site: '@juliaa_dev',
      creator: '@juliaa_dev',
      title: 'Julia A • Developer Portfolio',
      description: '',
      images: [`${env.SITE_URL}/og-image.png`],
    },
  },
};
